services:
  api1:
    image: ghcr.io/gandarez/rinha-de-backend-2026-gandarez-go:latest
    platform: linux/amd64
    hostname: api1
    environment:
      PORT: "9999"
      GOMAXPROCS: "1"
      GOMEMLIMIT: "140MiB"
    networks:
      - rinha
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"

  api2:
    image: ghcr.io/gandarez/rinha-de-backend-2026-gandarez-go:latest
    platform: linux/amd64
    hostname: api2
    environment:
      PORT: "9999"
      GOMAXPROCS: "1"
      GOMEMLIMIT: "140MiB"
    networks:
      - rinha
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"

  haproxy:
    image: haproxy:3.0-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

networks:
  rinha:
    driver: bridge
